### ISSUE TITLE
Typo in commands on README.md files

### ISSUE THREAD

**Issue by HaroldPetersInskipp** [prescient-devices/PD-Nodes#7]
There is a typo in the following files:
https://github.com/prescient-devices/PD-Nodes/blob/master/node-red-contrib-promptinput/README.md

    $ cd "${HOME}"/ode-red-contrib-promptinput

should be

    $ cd "${HOME}"/node-red-contrib-promptinput

and
https://github.com/prescient-devices/PD-Nodes/blob/master/node-red-contrib-downloadfile/README.md

    $ cd "${HOME}"/ode-red-contrib-downloadfile

should be

    $ cd "${HOME}"/node-red-contrib-downloadfile

**Comment by HaroldPetersInskipp** [comment]
To be clear, the typo occurs twice in each file.

**Comment by pmacostapdi** [comment]
Thank you for pointing this out. These typos have been fixed in 568d8c0aaf9027cbee0d4a2d8d6bbaeae71dc8ba and 84e76ab8d44c6b22e7693936fc2d2f735d838b2c.
